import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/redux/RedduxProvider";

import LeftBar from "@/components/appLayout/leftBar";
import TopBar from "@/components/appLayout/topBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-darkbg h-screen overflow-hidden`}
      >
        <ReduxProvider>
          <div className="h-[10%]">
            <TopBar />
          </div>
          <div className=" flex w-full h-[90%]">
            <div className="  text-white w-1/6 pt-3">
              <LeftBar />
            </div>
            <div className="w-5/6 overflow-auto h-full">{children}</div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
