import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/redux/RedduxProvider";
import SearchBar from "@/components/note/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="flex fixed justify-between w-screen h-[50px] bg-gray-600">
            <div className="text-white">icon</div>
            <SearchBar />
            <div className="text-white">tools</div>
          </div>
          <div className="flex fixed top-[50px] w-screen">
            <div className="w-44 bg-gray-600 h-screen text-white">left bar</div>
            <div className="w-full">{children}</div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
